In [1]:
import numpy as np
import pandas as pd
import xml.etree.ElementTree as ET

In [10]:
URL = 'http://www.casos.cs.cmu.edu/computational_tools/datasets/external/padgett/padgett.xml'

In [12]:
#!pip3 install wget
import wget

In [13]:
wget.download(URL, 'C:/Users/Anton/padgett_wget.xml')

100% [..........................................................] 46038 / 46038

'C:/Users/Anton/padgett_wget.xml'

In [71]:
tree = ET.parse("C:/Users/Anton/padgett_wget.xml")

In [72]:
root = tree.getroot()
tree

In [90]:
def pagerank(M, num_iterations = 100, d = 0.85):
    N = M.shape[1]
    x = np.random.rand(N, 1)
    x = x / np.linalg.norm(x, 1)
    M_hat = (d * M + (1 - d) / N)
    for i in range(num_iterations):
        x = M_hat @ x
    return x / x.sum()

In [91]:
def printing(name, data):
    print(name)
    display(data)

In [92]:
names = []
for i in tree.findall('MetaNetwork/nodes/nodeclass/node'):
    names.append(i.attrib.get('id'))
names

np.random.seed(5)

data_padgm = pd.DataFrame(np.random.randn(16, 16), index=names, columns=names)
links_padgm = tree.findall("MetaNetwork/networks/network[@id = 'PADGM']")[0].findall('link')
for link in links_padgm:
    data = link.attrib
    data_padgm.loc[data.get('source'), data.get('target')] = data.get('value')

data_padgb = pd.DataFrame(np.random.randn(16, 16), index=names, columns=names)
links_padgb = tree.findall("MetaNetwork/networks/network[@id = 'PADGB']")[0].findall('link')
for link in links_padgb:
    data = link.attrib
    data_padgb.loc[data.get('source'), data.get('target')] = data.get('value')

In [93]:
printing('PADGM', data_padgm)

PADGM

,ACCIAIUOL,ALBIZZI,BARBADORI,BISCHERI,CASTELLAN,GINORI,GUADAGNI,LAMBERTES,MEDICI,PAZZI,PERUZZI,PUCCI,RIDOLFI,SALVIATI,STROZZI,TORNABUON
ACCIAIUOL,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
ALBIZZI,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
BARBADORI,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
BISCHERI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000
CASTELLAN,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000
GINORI,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
GUADAGNI,0.0000,1.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
LAMBERTES,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
MEDICI,1.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,1.0000
PAZZI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000
PERUZZI,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000
PUCCI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
RIDOLFI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000
SALVIATI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
STROZZI,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,1.0000,0.0000,0.0000,0.0000
TORNABUON,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000

In [94]:
printing('PADGB', data_padgb)

PADGB

,ACCIAIUOL,ALBIZZI,BARBADORI,BISCHERI,CASTELLAN,GINORI,GUADAGNI,LAMBERTES,MEDICI,PAZZI,PERUZZI,PUCCI,RIDOLFI,SALVIATI,STROZZI,TORNABUON
ACCIAIUOL,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
ALBIZZI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
BARBADORI,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,1.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000
BISCHERI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000
CASTELLAN,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000
GINORI,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
GUADAGNI,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
LAMBERTES,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000
MEDICI,0.0000,0.0000,1.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,1.0000
PAZZI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
PERUZZI,0.0000,0.0000,1.0000,1.0000,1.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
PUCCI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
RIDOLFI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
SALVIATI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
STROZZI,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
TORNABUON,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [95]:
padgm_arr = data_padgm.to_numpy(dtype='float')
div = padgm_arr.sum(axis=1)
for i in range(len(div)):
    if div[i] == 0:
        div[i] += 1
pr_padgm = pagerank(padgm_arr / div)
prm_padgm = np.reshape(pr_padgm, (1, 16))[0]

In [96]:
padgb_arr = data_padgb.to_numpy(dtype='float')
div = padgb_arr.sum(axis=1) 
for i in range(len(div)):
    if div[i] == 0:
        div[i] += 1
pr_padgb = pagerank(padgb_arr / div)
pr_padgb = np.reshape(pr_padgb, (1, 16))[0]

In [97]:
relations = pd.DataFrame({"Marriage" : prm_padgm, "Business" : pr_padgb, "Total weighted" : (prm_padgm + pr_padgb) / 2}, index=names)
relation.sort_values(by="Total weighted", ascending=False)

           Marriage  Business  Total weighted
MEDICI     0.144793  0.176328        0.160561
PERUZZI    0.067404  0.113423        0.090414
BARBADORI  0.049782  0.122181        0.085981
GUADAGNI   0.097564  0.060577        0.079071
CASTELLAN  0.068803  0.087126        0.077965
BISCHERI   0.068375  0.086898        0.077637
LAMBERTES  0.030351  0.113237        0.071794
TORNABUON  0.070771  0.041058        0.055914
SALVIATI   0.060403  0.041058        0.050730
GINORI     0.031812  0.068147        0.049980
STROZZI    0.087627  0.009782        0.048704
ALBIZZI    0.078289  0.009782        0.044035
RIDOLFI    0.069115  0.009782        0.039448
PAZZI      0.035330  0.041058        0.038194
ACCIAIUOL  0.030129  0.009782        0.019955
PUCCI      0.009451  0.009782        0.009616

So we can conclude that Medici family has the best rank